name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t authorization-fivem-v2 .
        docker tag authorization-fivem-v2:latest felipeex/fivem-shop-authorization-fivem-v2:latest
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push felipeex/fivem-shop-authorization-fivem-v2:latest

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull felipeex/fivem-shop-authorization-fivem-v2:latest
          CONTAINER_ID=$(docker create felipeex/fivem-shop-authorization-fivem-v2:latest)
          mkdir authorization-fivem-v2
          chmod -R 777 /fivem-shop-payments
          docker cp $CONTAINER_ID:/app/authorization-fivem-v2/docker-compose.yml /authorization-fivem-v2
          docker rm $CONTAINER_ID
          docker-compose -f /authorization-fivem-v2 down
          docker-compose -f /authorization-fivem-v2 up -d
          docker image prune -f