name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t authorization-fivem-v2 .
        docker tag authorization-fivem-v2:latest felipeex/fivem-shop-authorization-fivem-v2:latest
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push felipeex/fivem-shop-authorization-fivem-v2:latest

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull felipeex/fivem-shop-authorization-fivem-v2:latest
          docker-compose down
          docker-compose up -d